export default {
  // Login
  REQUEST_LOGIN: "REQUEST_LOGIN",
  LOGIN_ERROR: "LOGIN_ERROR",
  LOGIN_SUCCESSFULLY: "LOGIN_SUCCESSFULLY",
  SET_ERROR_MESSAGE: "SET_ERROR_MESSAGE",
  CLEAR_ERROR_LOGIN: "CLEAR_ERROR_LOGIN",
  SET_AUTHENTICATION: "SET_AUTHENTICATION",
  RESET_AUTHENTICATION: "RESET_AUTHENTICATION",

  // Meta Data
  SET_ROUTER_CALLBACK: "SET_ROUTER_CALLBACK",
  START_APP_LOADING: "START_APP_LOADING",
  STOP_APP_LOADING: "STOP_APP_LOADING",
  SET_META_DATA: "SET_META_DATA",

  GENERAL_LOADING_RESET: "GENERAL_LOADING_RESET",
  GENERAL_LOADING_STARTED: "GENERAL_LOADING_STARTED",
  GENERAL_LOADING_STOPPED: "GENERAL_LOADING_STOPPED",
  GENERAL_MODAL_VIEW_IMAGE_OPEN: "GENERAL_MODAL_VIEW_IMAGE_OPEN",
  GENERAL_MODAL_VIEW_IMAGE_CLOSE: "GENERAL_MODAL_VIEW_IMAGE_CLOSE",
};
